#python create_saregama_playlists.py sanzgiri saregama_anand_bakshi saregama/anand_bakshi.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_asha saregama/asha.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_blues saregama/blues.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_classical saregama/classical.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_ghazal saregama/ghazal.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_gulzar saregama/gulzar.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_happy saregama/happy.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_hemant_geeta saregama/hemant_geeta.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_jagjit saregama/jagjit.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_javed_kaifi saregama/javed_kaifi.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_kalyan_anand saregama/kalyan_anand.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_kishore saregama/kishore.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_lata saregama/lata.txt 1 0
python create_saregama_playlists.py sanzgiri saregama_laxmi_pyare saregama/laxmi_pyare.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_madan_mohan saregama/madan_mohan.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_majrooh saregama/majrooh.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_manna_dey saregama/manna_dey.txt 1 0
python create_saregama_playlists.py sanzgiri saregama_mukesh saregama/mukesh.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_naushad saregama/naushad.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_opnayyar saregama/opnayyar.txt 1 0
python create_saregama_playlists.py sanzgiri saregama_rafi saregama/rafi.txt 1 0
python create_saregama_playlists.py sanzgiri saregama_rd_burman saregama/rd_burman.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_romantic saregama/romantic.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_sad saregama/sad.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_sahir saregama/sahir.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_sd_burman saregama/sd_burman.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_shakti saregama/shakti.txt 1 0
python create_saregama_playlists.py sanzgiri saregama_shankar_jai saregama/shankar_jai.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_spiritual saregama/spiritual.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_sufi saregama/sufi.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_talat_mahmood saregama/talat_mahmood.txt 1 0
#python create_saregama_playlists.py sanzgiri saregama_top300 saregama/top300.txt 1 0
